apiVersion: apps/v1
kind: Deployment
metadata:
  name: "jenkins-master-deployment"
  namespace: "jenkins"
  labels: 
    app: jenkins-master
    version: "latest"
spec:
  replicas: 1
  selector:
      matchLabels:
        app: "jenkins-master"
        version: "latest"
  template:
    metadata:
      labels:
        app: jenkins-master
        version: "latest"
    spec:
      containers:
        - name: "jenkins-master"
          image: "devopsart1/jenkins-master:latest"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
          ports:
            - name: http-port
              containerPort: 8080
            - name: jnlp-port
              containerPort: 50000
          volumeMounts:
            - name: jenkins-home
              mountPath: "/var/jenkins_home"
      volumes:
        - name: jenkins-home
          persistentVolumeClaim: 
            claimName: "jenkins-volume-claim"
            readOnly: false
