apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-volume
  namespace: "jenkins"
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/jenkins
